backend:
  name: github
  branch: master
  repo: semillistas/lujarweb
  base_url: https://gleaming-ethereal-slug.glitch.me
media_folder: public/img
public_folder: img
i18n:
  structure: multiple_files
  locales: [en, es]
collections:
  - name: "team_members"
    label: "Team member"
    create: true
    i18n: true
    folder: "team_members"
    fields:
      - { label: "Name", name: "name", widget: "string", i18n: duplicate }
      - { label: "Summary", name: "summary", widget: "string", i18n: true }
      - { label: "Featured Image", name: "thumbnail", widget: "image", i18n: duplicate }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
          - label: 'Cats'
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string"}
              - { label: "Description", name: "description", widget: "text"}